# Generated by Django 3.1.1 on 2020-09-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
